#!/usr/bin/env python3
"""Generate memos/README.md from _data/memos.yml; use --check in CI."""
import argparse
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "_data/memos.yml"
INDEX = ROOT / "memos/README.md"


def scalar(value):
    value = value.strip()
    if value in ("true", "false"):
        return value == "true"
    if re.fullmatch(r"-?\d+", value):
        return int(value)
    if len(value) >= 2 and value[0] == value[-1] == '"':
        return value[1:-1].replace('\\"', '"').replace("\\\\", "\\")
    return value


def load_memos(path=DATA):
    """Read the scalar-only records used by this memo catalog."""
    memos, current = [], None
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        match = re.match(r"^- (\w+):\s*(.*)$", line)
        if match:
            current = {}
            memos.append(current)
        else:
            match = re.match(r"^\s+(\w+):\s*(.*)$", line)
        if not match or current is None:
            raise ValueError(f"Cannot read catalog line: {line!r}")
        current[match[1]] = scalar(match[2])
    numbers = [memo["number"] for memo in memos]
    if not numbers or any(type(n) is not int or n < 0 for n in numbers) or len(numbers) != len(set(numbers)):
        raise ValueError("Memo numbers must be unique nonnegative integers")
    return sorted(memos, key=lambda memo: memo["number"])


def validate(memos):
    paths = set()
    for memo in memos:
        target = memo.get("file") or memo.get("url")
        if memo["status"] == "announced":
            if target:
                raise ValueError(f"Announced memo {memo['number']} must not have a download link")
        elif not target:
            raise ValueError(f"Memo {memo['number']} is missing a download link")
        if memo.get("file"):
            path = ROOT / memo["file"]
            if not path.is_file() or path.parent != ROOT / "memos":
                raise ValueError(f"Missing current memo: {path}")
            paths.add(path)
    if paths != set((ROOT / "memos").glob("*.pdf")):
        raise ValueError("The catalog and current memo PDFs disagree")


def render(memos):
    lines = [
        "<!-- Generated by scripts/build_memo_index.py. -->", "",
        "# Memo index", "",
        "Memo numbers and titles remain unchanged. Unused numbers remain gaps in the series.",
        "The [website](https://wvurail.org/lightwork/) groups current guides by topic.",
        "See [earlier PDF revisions](history/) and [editable originals](../sources/memos/).", "",
        "| Memo | Title | Status |", "| --- | --- | --- |",
    ]
    flags = {"active": "Published", "draft": "Under construction", "superseded": "Superseded",
             "announced": "Announced; PDF not yet contributed"}
    expected = 0
    for memo in memos:
        while expected < memo["number"]:
            lines.append(f"| {expected:03d} | Never used | — |")
            expected += 1
        expected = memo["number"] + 1
        title = memo["title"].replace("|", "\\|")
        target = memo.get("url")
        if memo.get("file"):
            target = Path(memo["file"]).name
        if target:
            title = f"[{title}]({target})"
        status = flags[memo["status"]]
        if memo.get("superseded_by"):
            status += f" by memo {memo['superseded_by']:03d}"
        if memo.get("supersedes"):
            status += f"; replaces memo {memo['supersedes']:03d}"
        lines.append(f"| {memo['number']:03d} | {title} | {status} |")
    lines += ["", "Titles, authors, descriptions, and publication notes are maintained in",
              "[_data/memos.yml](../_data/memos.yml).", "",
              "Follow the [contribution guide](../CONTRIBUTING.md) when adding a memo or revision.", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    memos = load_memos()
    validate(memos)
    content = render(memos)
    if args.check:
        if not INDEX.exists() or INDEX.read_text(encoding="utf-8") != content:
            raise SystemExit("Run python3 scripts/build_memo_index.py to update the memo index")
        print(f"Memo index is current: {len(memos)} records")
    else:
        INDEX.write_text(content, encoding="utf-8")
        print(f"Wrote memo index: {len(memos)} records")


if __name__ == "__main__":
    main()
